# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('available', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('tag', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('request_quantity', models.SmallIntegerField()),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('time_requested', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Question'),
        ),
    ]
