# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('available', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('price', models.FloatField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('request_quantity', models.SmallIntegerField()),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('time_requested', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
