# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170123_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
