# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170123_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='item_name',
        ),
    ]
