# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170124_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.CharField(default='196cb49b', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
