# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20170124_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.CharField(default='cf9a4472-0164-4422-a194-a283b143de92', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
