# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170124_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.CharField(default='4d2955de-0c25-44ed-a873-75fd9649c769', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
